name: Build static library dependencies
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/**"
      - "Makefile"
jobs:
  prepare:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - shell: bash
        run: make deps.header
      - uses: actions/upload-artifact@v3
        with:
          name: duckdb_h
          path: duckdb.h
          retention-days: 1
  darwin_arm64:
    needs: prepare
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - shell: bash
        run: make deps.darwin.arm64
      - uses: actions/upload-artifact@v3
        with:
          name: darwin_arm64
          path: deps/darwin_arm64/libduckdb.a
          retention-days: 1
  commit:
    runs-on: ubuntu-latest
    needs: [darwin_arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - shell: bash
        run: |
          rm -f deps/darwin_arm64/libduckdb.a
          rm -f duckdb.h
      - uses: actions/download-artifact@v3
        with:
          name: duckdb_h
          path: .
      - uses: actions/download-artifact@v3
        with:
          name: darwin_arm64
          path: deps/darwin_arm64
      - name: Push static libraries
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Re-build static libraries
